version: '3.8'

networks:
  k6:
  grafana:
  prometheus:


services:
  prometheus:
    image: prom/prometheus:v2.35.0
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
    networks:
      - k6
      - grafrana
      - prometheus
    ports:
      - "9090:9090"

    grafana:
      image: grafana/grafana:8.5.3
      networks:
        - grafana
        - prometheus
      ports:
        - "3000:3000"
      enviroment:
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_ANONYMOUS_ENABLED=true
        -
      volumes:
        - ./home/adrian/TEST_DOCKER/grafana:/etc/grafana/provisioning/
k6:
  build: .
  networks:
    - k6
  ports:
    - "6565:6565"
  enviroment:
    - K6_PROMETHEUS_REMOTE_URL=http://prometheus:9090/api/v1/write
    - K6_OUT=output-prometheus-remote
  depends_on:
    - prometheus
  volumes:
    - /home/adrian/TEST_DOCKER/k6_scripts:/scripts
