version: '3.0'

services:
  db:
    image: timescaledev/timescaledb-ha:pg12-latest
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  prometheus:
    image: prom/prometheus:latest
    command: --enable-feature=remote-write-receiver --config.file=/etc/prometheus/prometheus.yml --web.config.file=/etc/prometheus/web_config.yml
    ports:
      - 9090:9090/tcp
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/web_config.yml:/etc/prometheus/web_config.yml
      - ${PWD}/tls.crt:/etc/prometheus/tls.crt
      - ${PWD}/tls.key:/etc/prometheus/tls.key
    restart: always

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
